Algoritmo "Portugol soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Comando de Entrada e Operadores em VisualALG
// Autor(a)    : Rafael
// Data atual  : 22/02/2022
Var
// Seção de Declarações das variáveis 
   N1,N2,soma : inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval("Digite um número: ")
leia(n1)
Escreval("Digite outro número: ")
leia(n2)
soma <- n1+n2
Escreval("Resultado:", n1, " + ", n2 ," = ",soma)




Fimalgoritmo