Algoritmo "Conversor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Conversor de Radiano para Seno
// Autor(a)    : Rafael
// Data atual  : 22/02/2022
Var
// Seção de Declarações das variáveis 
   angulo , S :real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      Escreval("informe um angulo:")
      leia(angulo)
      S<- sen(GraupRad(angulo))
      Escreval ("O seno de" , angulo, " é igual a", s)
Fimalgoritmo